---
#
# Installing Kibana
#

# Install Kibana 

- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes
 
# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: localhost'

- name: Setting public baseUrl
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.publicBaseUrl:'
   line: 'server.publicBaseUrl: "http://kibana.tm"'

- name: Defining server port
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: 5601'
    
- name: Defining Elasticsearch URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.hosts:'
   line: 'elasticsearch.hosts: ["http://localhost:9200"]'
   

- name: Defining Elasticsearch Enterprise URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'enterpriseSearch.host:'
   line: 'enterpriseSearch.host: "http://localhost:3002"'
   
# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
